generators/app/templates/src/projectName.jsx

Added a reminder of removing comments so that we don't need to comment this on every component pull request.
@cerner/terra

Update react template comment

---

generators/app/templates/examples/index.jsx
generators/app/templates/src/projectName.scss

Update the generator with the doc site moving to a package.
https://github.com/cerner/terra-ui/issues/73
@cerner/terra

update with doc site move

---

generators/app/templates/src/projectName.scss

https://github.com/cerner/terra-ui/pull/77
@cerner/terra

Update mixins import

---

README.md
generators/app/templates/package.json

Updates to the generator to support some performance improvements in terra-toolkit.

Updates to generator for terra-toolkit

---

generators/app/templates/package.json

https://github.com/cerner/terra-ui/pull/134
@cerner/terra

Update packages to start at 0.0.0

---

generators/app/templates/README.md
test/app.js

https://github.com/cerner/terra-ui/pull/135
@cerner/terra

Update link to documentation

---

generators/app/templates/README.md
generators/app/templates/package.json
test/app.js

Update terra-ui to terra-core
@cerner/terra
https://github.com/cerner/generator-terra-module/issues/26

terra-ui => terra-core

---

generators/app/index.js
generators/app/templates/_.npmignore
test/app.js

https://github.com/cerner/generator-terra-module/issues/36
@cerner/terra

Add npmignore

---

generators/app/templates/package.json

https://github.com/cerner/generator-terra-module/issues/33
@cerner/terra

Update the compile:clean script to use rimraf

---

generators/app/templates/package.json

Add terra-base as peer dependency

---

README.md
generators/app/templates/docs/themeable-variables.md
generators/app/templates/projectNameTests.jsx
generators/app/templates/tests/nightwatch.conf.js

A few changes have been made before releasing the generator. 
1. The README was updated to included instructions on updating the generator.
2. The relative path for terra-toolkit was removed in the webpack config file.
3. Added Project Name to Themeable Variables doc.
@cerner/terra

Few Updates before Release

---

generators/app/templates/terra-clinical-package.json

Remove terra-toolkit from terra-clinical devDependencies

---

generators/app/templates/terra-clinical-package.json
generators/app/templates/terra-package.json

Set lower bound for react and react-dom version to 15.4.2

---

generators/app/templates/terra-clinical-package.json
generators/app/templates/terra-package.json
test/app.js

Adding script for props-table to the generator.
https://github.com/cerner/terra-core/pull/473
https://github.com/cerner/terra-clinical/pull/107
@cerner/terra

props-table-cli

---

generators/app/templates/docs/README.md

Update docs README with component features section

Update docs README with component features section

---

generators/app/templates/projectName-spec.js
generators/app/templates/terra-clinical-package.json
generators/app/templates/terra-consumer-package.json
generators/app/templates/terra-package.json
test/app.js

Update for the newest changes in [terra-toolkit v2.0 release](https://github.com/cerner/terra-toolkit/pull/8).
Additionally, changes were made for [terra-base v2.0 release](https://github.com/cerner/terra-core/pull/738).
@cerner/terra

Nightwatch changes for Toolkit 2.0

---

CHANGELOG.md
generators/app/templates/terra-clinical-package.json
generators/app/templates/terra-consumer-package.json
generators/app/templates/terra-package.json

This PR:
- Updates the jest scripts to reflect changes made for Jest version bump to v2.0.2
- Adds Changelog

Update Jest Scripts & Add Changelog

---

.npmrc
CHANGELOG.md
generators/app/index.js
generators/app/templates/CHANGELOG.md
generators/app/templates/projectNameTestRoutes.jsx
generators/app/templates/projectNameTests.jsx
generators/app/templates/src/projectName.scss
generators/app/templates/terra-clinical-package.json
generators/app/templates/terra-consumer-package.json
generators/app/templates/terra-package.json
test/app.js

Some updates that needed made:
- Update package scripts for windows https://github.com/cerner/terra-core/issues/217
- Remove 'selector-class-pattern' rule from sass template https://github.com/cerner/terra-core/issues/812 & https://github.com/cerner/terra-clinical/issues/193
- Remove _variables.scss & _mixins.scss file creation. Most packages no longer use these files.
@cerner/terra

Generator Updates

---

generators/app/index.js
test/app.js

Change generated name for terra-framework packages

---

generators/app/templates/src/projectName.jsx

Added semi-colon to fix lint error in generated package.
Fix an error causing generated packages to fail builds.
Please add your name to the [CONTRIBUTORS.md] file. Adding your name to the [CONTRIBUTORS.md] file signifies agreement to all rights and reservations provided by the [License].
@cerner/terra

Fix lint error

---

generators/app/templates/projectNameTest.jsx
generators/app/templates/src/projectName.jsx

Add name property back in as content so tests pass in generated code.
@cerner/terra

Fix broken tests.

---

CHANGELOG.md
generators/app/index.js
generators/app/templates/Index.jsx
generators/app/templates/package.json
test/app.js

Use React 16 & Remove PropsTable Script

---

CHANGELOG.md
generators/app/templates/_.npmignore

Do not publish snapshots to NPM.
@cerner/terra

Ignore snapshots

---

CHANGELOG.md
CONTRIBUTORS.md
generators/app/templates/package.json

Changing the generator file to use the the new javascript jest config
@cerner/terra

Updating generator script to use new js file instead of json

---

CHANGELOG.md
generators/app/templates/package.json

Remove terra-base from dependencies. Closes #97.

Update base dependency

---

CHANGELOG.md
generators/app/index.js
package.json

This is part of the work need towards resolving the dependency / devDependency issue https://github.com/cerner/generator-terra-module/issues/107

Replaced dependency on lodash with modularized lodash packages

---

CHANGELOG.md
generators/app/templates/package.json

Resolves https://github.com/cerner/terra-core/issues/1818

Bump react and react-dom minimum peerDependency version

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md

Update issue template to include mentions of terra members that have been worked with so far.

Update issue template

---

CONTRIBUTORS.md
generators/app/templates/CHANGELOG.md
generators/app/templates/package.json
package.json

Updated the react and react-dom dependency versions
Resolves [#119](https://github.com/cerner/generator-terra-module/issues/119)

Updated react dependency versions

---

CHANGELOG.md
CONTRIBUTORS.md
generators/app/templates/tests/moduleName-spec.js

Update generated test template.

---

CHANGELOG.md
generators/app/templates/README.md
generators/app/templates/_.npmignore
generators/app/templates/package.json
generators/app/templates/tests/moduleName-spec.js
test/app.js

Make Changes for Toolkit v5 & Babel 7

Make Changes for Toolkit v5 & Babel 7

---

CHANGELOG.md
CONTRIBUTORS.md
generators/app/templates/tests/moduleName-spec.js

Also minor changelog cleanup and adding myself to contributors list
Not sure if it really needs my changelog entry since the broken code never got released but

Fix syntax errors in generated WDIO script

---

CHANGELOG.md
CONTRIBUTORS.md
generators/app/templates/package.json

Update version of terra-doc-template

---

CHANGELOG.md
generators/app/templates/package.json
generators/app/templates/wdio.conf.js
test/app.js

Update test commands used by new mono-repo packages.
@cerner/terra

Update Test commands

---

CHANGELOG.md
package.json

Testing out [`eslint-config-terra` update](https://github.com/cerner/eslint-config-terra/pull/34)
Changes include:
* Updated ESLint version
* Updating ESLint config version

ESLint 6 Update

---

CHANGELOG.md
CONTRIBUTORS.md
package.json

Updated the eslint-config-terra dependency from v^3.0.0 to @cerner/eslint-config-terra v^4.0.0, along with the associated config.
Closes #143 
Thank you for contributing to Terra.
@cerner/terra

Update eslint config terra dependency

---

.github/workflows/label.yml
.travis.yml
CONTRIBUTING.md
README.md
RELEASE.md
generators/app/templates/README.md
generators/app/templates/docs/README.md
generators/app/templates/src/terra-dev-site/ChangeLog.jsx
generators/app/templates/src/terra-dev-site/Index.jsx
test/app.js

Setup main
Closes #145
Automated in branch.
This need merged before any other PRs since the default branch is now main.
Thank you for contributing to Terra.
@cerner/terra

master -> main
